apiVersion: v2
name: website
description: The main Waldo website
type: application

icon: https://raw.githubusercontent.com/waldo-vision/waldo/master/apps/web/public/android-chrome-256x256.png
home: https://waldo.vision
sources:
  - https://github.com/waldo-vision/waldo-helm/tree/main/charts/website
  - https://github.com/waldo-vision/waldo/tree/master/apps/web

# chart version, should follow semver
version: 0.8.0

# app version its targeting
appVersion: "0.0.3"

keywords:
  - website
  - waldo-vision

