apiVersion: v2
name: website
description: The main Waldo website
type: application

icon: https://raw.githubusercontent.com/waldo-vision/waldo/master/apps/web/public/android-chrome-256x256.png
home: https://waldo.vision
sources:
  - https://github.com/waldo-vision/waldo-helm/tree/main/charts/website
  - https://github.com/waldo-vision/waldo/tree/master/apps/web

# chart version, should follow semver
version: 0.5.0

# app version its targeting
appVersion: "0.0.1-alpha.10"

keywords:
  - website
  - waldo-vision

dependencies:
  - name: http-redis
    repository: https://waldo-vision.github.io/waldo-helm/
    version: "*"
    alias: http-redis
