# Default values for website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: ghcr.io/waldo-vision/web
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""
  pullPolicy: IfNotPresent

migrateImage:
  repository: ghcr.io/waldo-vision/migrate
  # Overrides the image tag whose default is the chart appVersion.
  # tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

secret:
  # name of the secret
  name: "waldo-website-secrets"
  # whether to use our in built secrets file or not
  useBuiltInSecret: true

# These are the env vars passed here:
# https://github.com/waldo-vision/waldo/blob/master/apps/web/.env.example
# all of these values are stored as secrets
# see secret format in templates/secret.yaml
#
# These values below MUST be defined else the
# deployment won't pull env vars as secrets.
# They can be blank and defined in your own
# secrets file. Just remember to disable
# "secret.useBuiltInSecret"
env:
  # discord
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""

  # google
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""

  YOUTUBE_API_KEY: ""

  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""

  BTLNET_CLIENT_ID: ""
  BTLNET_CLIENT_SECRET: ""

  TWITCH_CLIENT_ID: ""
  TWITCH_CLIENT_SECRET: ""

  FB_CLIENT_ID: ""
  FB_CLIENT_SECRET: ""

  # cloudflare
  CLOUDFLARE_TURNSTILE_SECRET: ""
  NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY: ""

  # database
  DATABASE_URL: ""

  # next auth
  NEXTAUTH_URL: ""
  NEXTAUTH_SECRET: ""

  # # upstash
  # UPSTASH_REDIS_REST_URL: ""
  # UPSTASH_REDIS_REST_TOKEN: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "waldo-website"

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
