apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "website.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "website.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "website.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # if any changes are made, make sure to update secret.yaml and values.yaml
          env:
            # discord
            - name: "DISCORD_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  client-id
                  name: {{ .Release.Name }}-discord
            - name: "DISCORD_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  client-secret
                  name: {{ .Release.Name }}-discord

            # google
            - name: "GOOGLE_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  client-id
                  name: {{ .Release.Name }}-google
            - name: "GOOGLE_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  client-secret
                  name: {{ .Release.Name }}-google
            - name: "YOUTUBE_API_KEY"
              valueFrom:
                secretKeyRef:
                  key:  yt-api-key
                  name: {{ .Release.Name }}-google

            # github
            - name: "GITHUB_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  client-id
                  name: {{ .Release.Name }}-github
            - name: "GITHUB_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  client-secret
                  name: {{ .Release.Name }}-github

            # battle.net
            - name: "BTLNET_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  client-id
                  name: {{ .Release.Name }}-btlnet
            - name: "BTLNET_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  client-secret
                  name: {{ .Release.Name }}-btlnet

            # twitch
            - name: "TWITCH_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  client-id
                  name: {{ .Release.Name }}-twitch
            - name: "TWITCH_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  client-secret
                  name: {{ .Release.Name }}-twitch

            # facebook
            - name: "FB_CLIENT_ID"
              valueFrom:
                secretKeyRef:
                  key:  client-id
                  name: {{ .Release.Name }}-facebook
            - name: "FB_CLIENT_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  client-secret
                  name: {{ .Release.Name }}-facebook

            # cloudflare
            - name: "CLOUDFLARE_TURNSTILE_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  turnstile-secret
                  name: {{ .Release.Name }}-cloudflare
            - name: "CLOUDFLARE_TURNSTILE_SITE_KEY"
              valueFrom:
                secretKeyRef:
                  key:  turnstile-site-key
                  name: {{ .Release.Name }}-cloudflare

            # database
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  key:  url
                  name: {{ .Release.Name }}-database

            # nextauth
            - name: "NEXTAUTH_URL"
              valueFrom:
                secretKeyRef:
                  key:  url
                  name: {{ .Release.Name }}-nextauth
            - name: "NEXTAUTH_SECRET"
              valueFrom:
                secretKeyRef:
                  key:  secret
                  name: {{ .Release.Name }}-nextauth

            # upstash
            - name: "UPSTASH_REDIS_REST_URL"
              valueFrom:
                secretKeyRef:
                  key:  url
                  name: {{ .Release.Name }}-upstash
            - name: "UPSTASH_REDIS_REST_TOKEN"
              valueFrom:
                secretKeyRef:
                  key:  token
                  name: {{ .Release.Name }}-upstash

          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
