
{{ if .Values.secret.useBuiltInSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{ end }}
