apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discord
data:
  clientId: {{ .Values.siteConfig.discord.clientId | b64enc }}
  clientSecret: {{ .Values.siteConfig.discord.clientSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google
data:
  clientId: {{ .Values.siteConfig.google.clientId | b64enc }}
  clientSecret: {{ .Values.siteConfig.google.clientSecret | b64enc }}
  ytApiKey: {{ .Values.siteConfig.google.ytApiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-github
data:
  clientId: {{ .Values.siteConfig.github.clientId | b64enc }}
  clientSecret: {{ .Values.siteConfig.github.clientSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-btlnet
data:
  clientId: {{ .Values.siteConfig.btlnet.clientId | b64enc }}
  clientSecret: {{ .Values.siteConfig.btlnet.clientSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-twitch
data:
  clientId: {{ .Values.siteConfig.twitch.clientId | b64enc }}
  clientSecret: {{ .Values.siteConfig.twitch.clientSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-facebook
data:
  clientId: {{ .Values.siteConfig.facebook.clientId | b64enc }}
  clientSecret: {{ .Values.siteConfig.facebook.clientSecret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloudflare
data:
  turnstileSecret: {{ .Values.siteConfig.cloudflare.turnstileSecret | b64enc }}
  turnstileSiteKey: {{ .Values.siteConfig.cloudflare.turnstileSiteKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database
data:
  url: {{ .Values.siteConfig.database.url | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nextauth
data:
  url: {{ .Values.siteConfig.nextauth.url | b64enc }}
  secret: {{ .Values.siteConfig.nextauth.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-upstash
data:
  url: {{ .Values.siteConfig.upstash.url | b64enc }}
  token: {{ .Values.siteConfig.upstash.token | b64enc }}
