
{{ if .Values.secret.useBuiltInSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  {{- range $key, $val := .Values.env }}

  # if key is "HASH_SALT"
  {{ if eq $key "HASH_SALT" }}
  # there is a default value
  {{ $key }}: {{ default (randAlphaNum 50 | quote) $val | b64enc }}
  # else, treat it like normal
  {{ else }}
  {{ $key }}: {{ $val | b64enc }}
  {{ end }}

  {{- end}}
{{ end }}
